---

name: Debian13-CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore
      - ./meta/main.yml

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore

permissions:
  contents: read

jobs:
  debian13-ci:
    uses: philnewm/ansible-role-repo-control/.github/workflows/molecule-ci-podman.yml@main
    with:
      scenario_name: debian13

...
